<!-- Code qui marche et qu'il faut uiliser au cas où on veut enregistrer des informations dans votre liste
     de n’ importe où dans votre site internet où l'on a inséré le block. Il est associé avec  la fonction save de Monblock.php -->
<!-- <form action="//echo $this->save(); ?>" method="post"> -->
<form action="<?php echo 'http://wp.challinge.net/magento-rpc/magento/test/index/save'; ?>" method="post">
    <fieldset>
        <ul>
            <li>
                <label for="nom">Nom</label>
                <input type="text" id="nom" name="nom" />
            </li>
            <li>
                <label for="prenom ">Prenom</label>
                <input type="text" id="prenom" name="prenom" />
            </li>
            <li>
                <label for="nom">Telephone</label>
                <input type="text" id="telephone" name="telephone" />
            </li>
            <li>
                <input type="submit" value="Save" />
            </li>
        </ul>
    </fieldset>
</form>
<?php
echo $this->methodblock();
?>